export const IS_PRODUCTION = process.env.NEXT_PUBLIC_NODE_ENV === 'production'
export const MERGE_CANVAS_CONTRACT_ADDRESS =
	(IS_PRODUCTION ? process.env.NEXT_PUBLIC_MERGE_CANVAS_CONTRACT_ADDRESS : process.env.NEXT_PUBLIC_MERGE_CANVAS_CONTRACT_ADDRESS_DEV) as string
export const MERGE_NFT_CONTRACT_ADDRESS =
	(IS_PRODUCTION ? process.env.NEXT_PUBLIC_MERGE_NFT_CONTRACT_ADDRESS : process.env.NEXT_PUBLIC_MERGE_NFT_CONTRACT_ADDRESS_DEV) as string
