import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useAccount, useConnect } from 'wagmi';
import { useEffect, useRef } from 'react';
import { Board } from '../components/Board';

function Header({ children }: { children: JSX.Element | JSX.Element[] }) {
    return (
        <header
            className="relative py-4 px-8 border-b border-eth-light-gray flex flex-row justify-between items-center"
            style={{
                boxShadow: '0 0 20px 1px rgba(30,30,30,0.2)',
                zIndex: 10000,
            }}
        >
            {children}
        </header>
    )
}

function Footer({ children }: { children: JSX.Element | JSX.Element[] }) {
    return (
        <footer className="p-4 bg-white text-center">
            {children}
        </footer>
    )
}

const Home: NextPage = () => {
    return (
        <div className="flex flex-col h-screen">
            <Head>
                <title className="text-eth-gray">The Merge Canvas</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header>
                <div className="text-2xl font-bold">The Merge Canvas</div>
                <div>
                    <ConnectButton
                        // chainStatus="none"
                        // showBalance={false}
                        // accountStatus="address"
                    />
                </div>
            </Header>
            <main className="flex grow justify-center bg-stone-50 py-12 px-4">
                <Board />
                {/*<DisplayNameComp />*/}
            </main>
            <Footer>
                <div className="text-eth-gray">
                    The Merge Canvas built with ❤️ by <a href="https://twitter.com/outlierdao">Outliers</a>
                </div>
            </Footer>
        </div>
    );
};

export default Home;
